#!/usr/bin/env bash

# ┏━━━━━━┓
# ┃ path ┃
# ┗━━━━━━┛

source "${HOME}/.config/tmux/status/globals"

main() {
  local component=""
  component+="#[fg=${COLORS[ORANGE]}]"
  component+="${ICONS[SHADE]} "
  component+="${ICONS[FOLDER]} "
  component+="#[fg=${COLORS[FOREGROUND]}]"
  component+="$(tmux display -p "#{pane_current_path}" | sed "s#^$HOME#~#") "

  echo "${component}"
}

main "$@"
