#!/usr/bin/env bash

# ┏━━━━━━━━┓
# ┃ window ┃
# ┗━━━━━━━━┛

source "$(tmux display-message -p "#{config_files}" | xargs dirname)/status/globals"

main() {
  local WINDOW_NUMBER="$1"
  local PANE_NUMBER="$2"

  local WINDOW_NUMBER_STYLE="$(convert_number_style "${WINDOW_NUMBER}" "${NUMBER_STYLES[PLAIN]}")"
  local PANE_NUMBER_STYLE="$(convert_number_style "${PANE_NUMBER}" "${NUMBER_STYLES[HOLLOW_SQUARE]}")"
  local ZOOMED_PANE_NUMBER_STYLE="$(convert_number_style "${PANE_NUMBER}" "${NUMBER_STYLES[HOLLOW_DOUBLE_SQUARE]}")"

  local component=""
  component+="#[fg=${COLORS[GRAY_6]}]"
  component+="  "
  component+="${ICONS[WINDOW]} "
  component+="${WINDOW_NUMBER_STYLE} "
  component+="#{window_name} "
  component+="#{?window_zoomed_flag,${ZOOMED_PANE_NUMBER_STYLE},${PANE_NUMBER_STYLE}} "
  component+="#{?window_last_flag,#[fg=${COLORS[GREEN]}]${ICONS[RESTORE]},${ICONS[DOT]}} "

  echo "${component}"
}

main "$@"
