# ┏━━━━━━━┓
# ┃ rules ┃
# ┗━━━━━━━┛

windowrule {
    opacity = 0.80 0.80
    match:class = ^(discord|spotify|steam|steamwebhelper)$
}

windowrule {
    opacity = 0.90 0.90
    match:class = ^(chromium)$
}

layerrule {
    name = no-anim-selection
    no_anim = on
    match:namespace = selection
}
