#!/usr/bin/env zsh

# ┏━━━━━━━━━┓
# ┃ aliases ┃
# ┗━━━━━━━━━┛

__zsh::config::aliases::misc() {
  if command -v nvim >/dev/null; then
    alias vim="nvim"
  fi

  if command -v trash >/dev/null; then
    alias rm="trash"
  fi

  if command -v lsd >/dev/null; then
    alias ls="lsd"
  fi

  if [[ -f /usr/lib/huiontablet/huiontablet.sh ]]; then
    alias huiontablet="/usr/lib/huiontablet/huiontablet.sh"
  fi
}

__zsh::config::aliases::general() {
  alias mkdir="mkdir -p"
}

() {
  __zsh::config::aliases::general
  __zsh::config::aliases::misc
}
